module.exports = [
  'Chendy Martika Jaya',
  'Joseline Olivia',
  'Stefanus Hodir',
  'Shela Oktania',
  'Adi Kusumah',
  'Rispandi Mandala Putra',
  'Fitria',
  'Corneleo Dimas Yulendra Wasisto',
  'Harmoko',
  'Melisa Aprilia',
  'Rubi Anggoro',
  'Agus Rianto Harjono',
  'Felix Firmansyah',
  'Gilbert Bagas Sadewo',
  'Hari Tri Mukti',
  'Arina Khujjatul Khaq',
  'Ranti Veronika Sidauruk',
  'Diki Darmawan',
  'Fattah Juliandoko',
  'Muhamad Rino Rifa\'i',
  'Rifky Fauzi',
  'Khrisna Rizky Meilarani',
  'Gedeon Enggar Satrio',
  'Bilkis Ismail',
  'Hendra Nur Solichin',
  'Audrey',
  'Marcel',
  'Joko Prihono',
  'Adelia Putri Ariansyah',
  'Herfian Pradityo',
  'Yogie Alfath',
  'Devi Erliani',
  'Muhamad Apriansyah Dimas Saputra',
  'Cokyat Christian',
  'Andi Aprian',
  'Eka Puteri Shelayanti',
  'Siska Kusmayanti',
  'Daniella Vannesa Chrissant Putri',
  'Alvin Julianto Liaunardi',
  'Gabriella Magdalena',
  'Carissa Christybella Wijaya',
  'Atina Balqis Izza',
  'Lanang Fajar Nugroho Budianto',
  'Rafida Afnan Azizi',
  'Iyan Hardiyansyah',
  'Bayu Sidik',
  'Diansyah',
  'Muhammad Ja\'i',
  'Nana Supriatna',
  'Priyadi',
  'Reza Sidqiaturohman',
  'Syaiful Eko Nurrohman',
  'Iwat',
  'Samsudin',
  'Ardiansyah',
  'Tegar Terthio Putra',
  'Lut Fatul Amanah',
  'Gilang Rizki Ramadhan',
  'Silmi Khoiriyah',
  'Alif Imanianto',
  'Hari Mulyanto',
  'Hari TM',
  'Agus RH',
  'Amalia',
  'Rino',
  'Dimas',
  'Iyan Hardiyansah',
  'Mahmudin',
  'Customer',
]
